name: ultimate-tic-tac-toe # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: ultimate-tic-tac-toe
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
website: https://github.com/Nokse22/ultimate-tic-tac-toe
license: GPL-3.0
source-code: https://github.com/Nokse22/ultimate-tic-tac-toe
issues: https://github.com/Nokse22/ultimate-tic-tac-toe/issues
contact: https://github.com/Nokse22/ultimate-tic-tac-toe
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ultimate-tic-tac-toe:
    plugin: meson
    source: https://github.com/Nokse22/ultimate-tic-tac-toe.git
    source-tag: 'v0.1.3'
    source-depth: 1
    parse-info: [ usr/share/metainfo/io.github.nokse22.ultimate-tic-tac-toe.metainfo.xml ]
    build-packages:
      - blueprint-compiler
    meson-parameters:
      - --prefix=/snap/ultimate-tic-tac-toe/current/usr
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/ultimate-tic-tac-toe/current/usr/bin/ultimate-tic-tac-toe
      chmod +x $CRAFT_PART_INSTALL/snap/ultimate-tic-tac-toe/current/usr/bin/ultimate-tic-tac-toe
    organize:
      snap/ultimate-tic-tac-toe/current: .

slots:
  ultimate-tic-tac-toe:
    interface: dbus
    bus: session
    name: io.github.nokse22.ultimate-tic-tac-toe

apps:
  ultimate-tic-tac-toe:
    command: usr/bin/ultimate-tic-tac-toe
    extensions: [ gnome ]
    common-id: io.github.nokse22.ultimate-tic-tac-toe
    desktop: usr/share/applications/io.github.nokse22.ultimate-tic-tac-toe.desktop
    plugs:
      - network
